using Application.Dto;
using Domain.Entities;

namespace Application.Interfaces
{
    /// <summary>
    /// Здесь определены use-cases приложения.
    /// </summary>
    public interface IDivisionService
    {
        /// <summary>Получить все подразделения в виде иерархического дерева.</summary>
        IList<DivisionNode> GetHierarchyTree();

        /// <summary>
        /// Получить автогенерируемый номер записи.
        /// Серверная реализация.
        /// Можно заменить на реализацию на фронте.
        /// </summary>
        /// <param name="divisionId">Id подразделения.</param>
        /// <returns>Автогенерируемый номер.</returns>
        string GetAutogeneratedNumber(Guid divisionId);

        /// <summary>Создать новое подразделение под указанным родителем.</summary>
        /// <param name="parentId">Id родительского подразделения (null, если верхний уровень).</param>
        /// <param name="name">Название нового подразделения.</param>
        /// <returns>Созданная сущность подразделения.</returns>
        Division CreateDivision(Guid? parentId, string name);

        /// <summary>Удалить подразделение (и всех потомков) по идентификатору.</summary>
        void DeleteDivision(Guid id);

        /// <summary>Переместить подразделение под другого родителя (и, опционально, изменить порядок).</summary>
        /// <param name="id">Id перемещаемого подразделения.</param>
        /// <param name="newParentId">Id нового родительского подразделения (null, если на верхний уровень).</param>
        /// <param name="newOrder">Новая позиция в порядке у нового родителя (если не задано, добавляется в конец).</param>
        void MoveDivision(Guid id, Guid? newParentId, int? newOrder = null);

        /// <summary>Переименовать подразделение.</summary>
        void RenameDivision(Guid id, string newName);

        /// <summary>Экспортировать все подразделения в XML формат (строка XML).</summary>
        string ExportToXml();

        /// <summary>Импортировать подразделения из XML (заменяя текущие данные).</summary>
        void ImportFromXml(string xmlData);
    }
}