using Application.Dto;
using Application.Interfaces;
using Domain.Entities;
using Domain.Interfaces;

namespace Application.Services
{
    public class DivisionService : IDivisionService
    {
        private readonly IDivisionRepository _divisionRepo;
        private readonly IXmlExportService _xmlService;

        public DivisionService(IDivisionRepository divisionRepo, IXmlExportService xmlService)
        {
            _divisionRepo = divisionRepo;
            _xmlService = xmlService;
        }

        public IList<DivisionNode> GetHierarchyTree()
        {
            throw new NotImplementedException();
        }

        public string GetAutogeneratedNumber(Guid divisionId)
        {
            throw new NotImplementedException();
        }

        public Division CreateDivision(Guid? parentId, string name)
        {
            throw new NotImplementedException();
        }

        public void DeleteDivision(Guid id)
        {
            throw new NotImplementedException();
        }

        public void MoveDivision(Guid id, Guid? newParentId, int? newOrder = null)
        {
            throw new NotImplementedException();
        }

        public void RenameDivision(Guid id, string newName)
        {
            throw new NotImplementedException();
        }

        public string ExportToXml()
        {
            throw new NotImplementedException();
        }

        public void ImportFromXml(string xmlData)
        {
            throw new NotImplementedException();
        }
    }
}